---
- name: Install caddy(v2) webserver
  hosts: servers
  become: yes
  tasks:
    # Following https://caddyserver.com/docs/download#debian-ubuntu-raspbian
    - name: Ensure caddy PPA is installed
      apt_repository:
        repo: "deb [trusted=yes] https://apt.fury.io/caddy/ /"
        state: present
        update_cache: yes
    - name: Install caddy
      apt:
        pkg: caddy
        state: present
