---
- name: Clone repositories borrowed from host
  hosts: dev
  tags: [git, hostrequired]
  vars:
    git_repos:
      - path: ~/dev/ws/cv_jbd
      - path: ~/.password-store
        refs: -b master
      - path: ~/dev/ws/jiby.tech
      - path: ~/dev/ws/jiby.tech_gen
        refs: -b master
      - path: ~/dev/ws/qrxfil
  tasks:
    - name: Package repo bundle to data/ on host
      loop: "{{ git_repos }}"
      local_action:
        module: shell
        creates: "{{ playbook_dir}}/../data/{{ item.path | basename }}.bundle"
        cmd: "git -C {{ item.path }} bundle create {{ playbook_dir}}/../data/{{ item.path | basename }}.bundle  {{ item.refs|default('--all')}}"

    - name: Copy bundle file with owner and permissions
      loop: "{{ git_repos }}"
      copy:
        src: "{{ playbook_dir}}/../data/{{ item.path | basename }}.bundle"
        dest: /tmp/repos/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
    - name: Ensure repos are cloned created
      loop: "{{ git_repos }}"
      # Ideally use the git ansible module instead, but it doesn't do local-file-cloning like git CLI
      shell:
        creates: "{{ item.path }}"
        cmd: "git clone /tmp/repos/{{ item.path|basename }}.bundle {{ item.path }} {{ item.refs|default('-b master')}}"

# TODO: Detect if repo created already before bundle/copy/clone
