---
- hosts: all
  tags: x11
  tasks:
    - name: Ensure x11 is installed
      become: yes
      apt:
        pkg: lightdm
    - name: Ensure MATE desktop environment is installed
      tags: MATE
      become: yes
      apt:
        pkg: mate-desktop-environment
    - name: Ensure i3-wm is installed
      tags: [i3, never]  # Disabled by default
      become: yes
      apt:
        pkg: i3
    - name: Ensure desktop customizations are installed
      become: yes
      apt:
        pkg:
          - shiki-brave-theme
          - fonts-firacode
          # - blueman
