---
- hosts: all
  tags: dev
  tasks:
    - name: Ensure dev tools are installed
      become: yes
      apt:
        pkg:
          - htop
          - jq
          - curl
          - silversearcher-ag
