---
- hosts: all
  tags: dev
  tasks:
    - name: Ensure dev tools are installed
      become: yes
      apt:
        pkg:
          - build-essential
          - htop
          - jq
          - curl
          - silversearcher-ag
    - name: Ensure blog tools are installed
      tags: blog
      become: yes
      apt:
        pkg: hugo
    - name: Ensure rust is installed
      tags: rust
      shell:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/"
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        warn: false
