---
- name: Developer documentation  (debian manpages + ~/dev/doc)
  hosts: all
  tags: [dev, docs]
  tasks:
    - name: Ensure ~/dev/docs exists
      file:
        path: "{{home}}/dev/doc/"
        state: directory
        mode: '0755'
    # # Replaced by python3-doc debian package!
    # - name: Ensure unzip available for py3 docs download
    #   become: yes
    #   apt:
    #     pkg: unzip
    # - name: Get Python3 docs
    #   unarchive:
    #     src: https://docs.python.org/3/archives/python-3.8.2-docs-html.zip
    #     dest: "{{home}}/dev/doc/"
    #     remote_src: yes
    - name: Install GNU docs packages
      become: true
      apt:
        pkg:
          - python3-doc
          - ansible-doc
          - debmake-doc
          - doc-debian
          - bash-doc
