---
- name: Generic development tools (incl. language support)
  hosts: dev
  tags: dev
  tasks:
    - name: Ensure dev tools are installed
      become: yes
      apt:
        pkg:
          - build-essential
          - htop
          - jq
          - curl
          - silversearcher-ag
          - net-tools
          - tree
    - name: Ensure blog tools are installed
      tags: blog
      become: yes
      apt:
        pkg: hugo
    - name: Ensure rust is installed
      tags: rust
      shell:
        creates: "{{home}}/.cargo/bin/"
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        warn: false
