---
- name: Docker install and gogs
  tags: [docker, never]
  hosts: all
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    # Force 'buster' (debian stable) repo instead (testing not released)
    # From geerlingguy.docker #196
    # https://github.com/geerlingguy/ansible-role-docker/issues/196
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} buster {{ docker_apt_release_channel }}"
    docker_users:
      - "{{ ansible_user }}"
  roles:  # Become just for the role, not whole play
    - { role: geerlingguy.pip, become: yes }
    - { role: geerlingguy.docker, become: yes }
  tasks:
    - name: Install gogs docker-compose.yml in /opt/gogs/
      become: yes
      copy:
        src: "{{ playbook_dir}}/../server/gogs-compose/docker-compose.yml"
        dest: /opt/gogs/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'
    # From systemd ansible example
    # https://stackoverflow.com/a/40114458
    - name: Install gogs systemd unit file
      become: yes
      copy:
        src: "{{ playbook_dir}}/../server/gogs-compose/gogs-docker-compose.service"
        dest: /etc/systemd/system/gogs-docker-compose.service

    - name: Start gogs service
      become: yes
      systemd:
        name: gogs-docker-compose
        state: started
        daemon_reload: yes
