---
- name: Docker install and gitea
  tags: docker
  hosts: all
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    docker_users:
      - "{{ ansible_user }}"
  roles:  # Become just for the role, not whole play
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.pip, become: yes }
  tasks:
    - name: Reset ssh connection to allow user changes for docker group
      meta: reset_connection
