---
- name: Docker install and gogs
  tags: [docker, never]
  hosts: all
  become: yes
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    # Force 'buster' (debian stable) repo instead (testing not released)
    # From geerlingguy.docker #196
    # https://github.com/geerlingguy/ansible-role-docker/issues/196
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} buster {{ docker_apt_release_channel }}"
    docker_users:
      - "{{ ansible_user }}"
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
