---
- name: Docker install and gogs
  tags: [docker, never]
  hosts: all
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    # Force 'buster' (debian stable) repo instead (testing not released)
    # From geerlingguy.docker #196
    # https://github.com/geerlingguy/ansible-role-docker/issues/196
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} buster {{ docker_apt_release_channel }}"
    docker_users:
      - "{{ ansible_user }}"
  roles:  # Become just for the role, not whole play
    - { role: geerlingguy.pip, become: yes }
    - { role: geerlingguy.docker, become: yes }
  tasks:
    - name: Install gitea docker-compose.yml in /opt/gitea/
      become: yes
      copy:
        src: "{{ playbook_dir}}/../server/gitea-compose/docker-compose.yml"
        dest: /opt/gitea/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'
    # From systemd ansible example
    # https://stackoverflow.com/a/40114458
    - name: Install gitea systemd unit file
      become: yes
      copy:
        src: "{{ playbook_dir}}/../server/gitea-compose/gitea-docker.service"
        dest: /etc/systemd/system/gitea-docker.service

    - name: Start gitea service
      become: yes
      systemd:
        name: gitea-docker
        state: started
        daemon_reload: yes
