---
- name: Emacs and its config (via stow)
  hosts: dev
  tags: emacs
  tasks:
    - name: Install emacs (no X)
      become: true
      apt:
        name: emacs-nox
    - name: Install mu4e (emacs mail client)
      tags: mu4e
      become: true
      apt:
        name: mu4e
    - name: Install emacs (X11) is installed
      tags: x11
      become: true
      apt:
        name: emacs-gtk
    - name: Install dependencies of pdf-tools package
      tags: [pdftools, x11]
      become: true
      apt:
        pkg:
          - autoconf
          - automake
          - g++
          - gcc
          - libpng-dev
          - libpoppler-dev
          - libpoppler-glib-dev
          - libpoppler-private-dev
          - libz-dev
          - make
          - pkg-config
# Emacs-conf repo steps

    - name: Deploy the emacs-conf repo via stow
      shell:
        creates: "{{home}}/.emacs.d/jb/external-pkg-config.el"
        cmd: "stow --dir ~/dev/conf/jibyconf/stow --target {{home}}/ {{ item }}"
      loop:
        - emacs
        - emacs-vanilla
        - emacs-packages
        - emacs-external
    # Debian/Ubuntu emacs package ships a systemd user service in
    # /usr/lib/systemd/user/emacs.service, no need to unstow our own
    # in ~/.config/ (which is now broken due to systemd user daemon
    # login management, whatever that means)
    - name: Ensure emacs bootstrap script present
      blockinfile:
        path: "{{home}}/.emacs"
        create: yes
        marker: ";; {mark} ANSIBLE MANAGED BLOCK: boostrap emacsconf"
        block: |
          (package-initialize)
          (cd "~/.emacs.d/jb/")
          (load-file "bootstrap.el")
          (cd "~/")
    - name: Ensure emacs daemon service enabled
      systemd:
        scope: user
        name: emacs
        enabled: yes
    # Fetches plugin if needed
    - name: Load bootstrap emacs-config script
      tags: slow
      shell:
        creates: "{{home}}/.emacs.d/elpa/"
        cmd: |
          emacs --batch -l {{home}}/.emacs --kill
