---
- hosts: all
  tasks:
    - name: Install emacs (no X)
      become: true
      apt:
        name: emacs-nox
    - name: Install emacs (X11) is installed
      when: x11_enabled|bool
      become: true
      apt:
        name: emacs
    - name: Install dependencies of pdf-tools package
      when: x11_enabled|bool
      become: true
      apt:
        pkg:
          - autoconf
          - automake
          - g++
          - gcc
          - libpng-dev
          - libpoppler-dev
          - libpoppler-glib-dev
          - libpoppler-private-dev
          - libz-dev
          - make
          - pkg-config
    - name: Install full texlive distro
      when: x11_enabled|bool
      become: true
      apt:
        pkg: texlive-full

# Emacs-conf repo steps

    - name: Install git for emacs config cloning
      become: true
      apt:
        pkg: git
    - name: Ensure ~/dev/conf/ exists for emacs config
      file:
        path: /home/vagrant/dev/conf
        state: directory
        mode: '0755'
    - name: Check ~/dev/conf/emacs-config cloned
      register: emacsconf_folder
      stat:
        path: /home/vagrant/dev/conf/emacs-conf
    - name: Clone the emacs-conf repo from bundle
      when: not emacsconf_folder.stat.exists
      # Ideally use the git ansible module instead, but it doesn't do bundle-file-cloning like git CLI
      shell: git clone /vagrant/data/jiby-emacsconf.bundle /home/vagrant/dev/conf/emacs-conf -b stowage
    # # TODO: Register the remote bundle before fetching from it
    # - name: Update the emacs-conf repo from bundle
    #   when: emacsconf_folder.stat.exists and emacsconf_folder.stat.isdir
    #   shell: git fetch /vagrant/data/jiby-emacsconf.bundle /home/vagrant/dev/conf/emacs-conf -b stowage

    # TODO: Add the emacs-conf repo and deployment via stow
