---
- hosts: all
  tasks:
    - name: Install emacs (no X)
      apt:
        name: emacs-nox
    - name: Install emacs (X11) is installed
      when: x11_enabled|bool
      apt:
        name: emacs
    - name: Install dependencies of pdf-tools package
      when: x11_enabled|bool
      apt:
        pkg:
          - autoconf
          - automake
          - g++
          - gcc
          - libpng-dev
          - libpoppler-dev
          - libpoppler-glib-dev
          - libpoppler-private-dev
          - libz-dev
          - make
          - pkg-config
    - name: Install full texlive distro
      when: x11_enabled|bool
      apt:
        pkg: texlive-full

      


# TODO: Add the emacs-conf repo and stow
