---
# Adapted from
# https://github.com/berdario/dotfiles/blob/5df6a949cccf43e2c44b0077f067fb688dbd9d6f/setup/roles/common/tasks/main.yml#L212
- name: Install guix package manager
  hosts: all
  vars:
    guix:
      url: https://ftp.gnu.org/gnu/guix/guix-binary-1.2.0.x86_64-linux.tar.xz
      sha256: 58fecdbaa8bec3795930879fad4cf7c31d3291c363b6cced18e4f7008d7e0282
  tasks:
    - name: Install GPG for verification of Guix
      become: True
      apt:
        pkg: gnupg2

    - name: Get Ludovic Courtès gpg key for guix
      become: False
      command: gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-key 3CE464558A84FDC69DB40CFB090B11993D9AEBB5
      register: ludo_gpg
      changed_when: "'unchanged' not in ludo_gpg.stderr"

    - name: Check if guix is already installed
      stat:
        path: /gnu/store
      register: guixstore

    - name: Download guix
      when: not guixstore.stat.exists
      get_url:
        url: "{{guix.url}}"
        dest: /tmp/guix.tar.xz
        checksum: "sha256:{{guix.sha256}}"

    - name: Download guix signature
      when: not guixstore.stat.exists
      get_url:
        url: "{{guix.url}}.sig"
        dest: /tmp/guix.tar.xz.sig

    - name: Verify guix with gpg
      become: False
      when: not guixstore.stat.exists
      command: gpg2 --verify /tmp/guix.tar.xz.sig /tmp/guix.tar.xz
      changed_when: False

    - name: Unpack guix
      become: True
      unarchive:
        src: /tmp/guix.tar.xz
        dest: /
        creates: /gnu/store
        copy: no

    - name: Set up guixbuild group
      become: True
      group:
        name: guixbuild
        system: yes

    - name: Set up guix build users
      become: True
      user:
        name: "guixbuilder{{item}}"
        comment: "Guix build user {{item}}"
        shell: /usr/sbin/nologin
        groups: guixbuild
        home: /var/empty
        system: yes
      with_sequence: start=1 end=10 format=%02d

    - name: Install guix systemd service
      become: True
      file:
        src: /var/guix/profiles/per-user/root/current-guix/lib/systemd/system/guix-daemon.service
        dest: /etc/systemd/system/guix-daemon.service
        state: link

    - name: Enable guix service
      become: True
      service:
        name: guix-daemon
        state: started
        enabled: True

    # - name: Symlink guix executable
    #   file:
    #     src: /var/guix/profiles/per-user/root/current-guix/bin/guix
    #     dest: "{{home}}/bin/guix"
    #     state: link

    - name: Authorize guix substitutes
      become: True
      shell: /var/guix/profiles/per-user/root/current-guix/bin/guix archive --authorize < /var/guix/profiles/per-user/root/current-guix/share/guix/berlin.guix.gnu.org.pub
      changed_when: False
    - name: Deploy the guix config via stow
      shell:
        creates: "{{home}}/.config/guix/channels.scm"
        cmd: "stow --dir ~/dev/conf/jibyconf/stow --target {{home}}/ guix"
    - name: Update guix packages
      shell:
        cmd: /var/guix/profiles/per-user/root/current-guix/bin/guix pull
        creates: "{{home}}/.config/guix/current/"
        executable: /bin/bash
    - name: Ensure ~/.bashrc uses guix glibc locale
      blockinfile:
        path: "{{home}}/.bash_profile"
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK: guix profile"
        block: |
          export GUIX_PROFILE=$HOME/.guix-profile
          export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale
          export PATH=$HOME/.config/guix/current/bin:$PATH
          source $HOME/.config/guix/current/etc/profile
    - name: Download guix locale
      shell:
        creates: "{{home}}/.guix-profile/lib/locale"
        cmd: "{{home}}/.config/guix/current/bin/guix install glibc-utf8-locales"
        executable: /bin/bash
    # - name: Update guix packages
    #   shell:
    #     cmd: "{{home}}/bin/guix pull && {{home}}/bin/guix package -u"
    #     executable: /bin/bash
    # - name: Install emacs via guix
    #   shell:
    #     cmd: "{{home}}/bin/guix install emacs"
    #     executable: /bin/bash
