---
- hosts: all
  tasks:
    - name: Install git for jiby-config cloning
      become: true
      apt:
        pkg: git
    - name: Ensure ~/dev/conf/ exists for jiby-config
      file:
        path: "{{ ansible_env.HOME}}/dev/conf"
        state: directory
        mode: '0755'
    - name: Ensure jiby-conf repo created
      # Ideally use the git ansible module instead, but it doesn't do local-file-cloning like git CLI
      shell:
        creates: "{{ ansible_env.HOME}}/dev/conf/jiby-conf"
        cmd: "git clone /vagrant/ {{ ansible_env.HOME}}/dev/conf/jiby-conf"
    # # TODO: Register the remote bundle before fetching from it
    # - name: Update the emacs-conf repo from bundle
    #   when: emacsconf_folder.stat.exists and emacsconf_folder.stat.isdir
    #   shell: "git fetch /vagrant/data/jiby-emacsconf.bundle {{ ansible_env.HOME}}/dev/conf/emacs-conf -b stowage"

# Deployment via stow

    - name: Install stow for deployment of emacs conf
      become: true
      apt:
        pkg: stow
    - name: Deploy the bash config via stow
      shell:
        cmd: "stow --dir ~/dev/conf/jiby-conf/stow --target {{ ansible_env.HOME}}/ bash"
        creates: "{{ ansible_env.HOME}}/.jb_profile.sh"
    - name: Ensure ~/.bashrc sources jb_profile
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: bash commands"
        block: source ~/.jb_profile.sh
    - name: Deploy the git config via stow
      shell:
        cmd: "stow --dir ~/dev/conf/jiby-conf/stow --target {{ ansible_env.HOME}}/ git"
        creates: "{{ ansible_env.HOME}}/.gitconfig"
