---
- name: LaTeX distro (texlive-full)
  hosts: dev
  tags: [x11, latex]
  tasks:
    - name: Install full texlive distro
      become: true
      apt:
        pkg: texlive-full
    - name: Install pandoc document converter
      become: true
      apt:
        pkg: pandoc
