---
- hosts: all
  tasks:
    - name: Ensure password manager installed
      become: yes
      apt:
        pkg:
          - gpgv2
          - pass
          - git
          - pass-extension-otp
    - name: Ensure password manager X11 extensions installed
      when: x11_enabled
      become: yes
      apt:
        pkg:
          - suckless-tools
          - xdotool
    # TODO: Clone password manager repo
    # TODO: Port over the gpg key
