---
- name: Pipx for standalone python apps (sphinx, borgmatic)
  hosts: dev
  tags: pipx
  tasks:
    - name: Ensure pipx is installed
      become: yes
      apt:
        pkg: pipx
    - name: Ensure pipx is in $PATH
      blockinfile:
        path: "{{home}}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pipx"
        block: |
          export PATH="{{home}}/.local/bin:$PATH"
    - name: Ensure sphinx is installed via pipx
      tags: [dev, docs]
      shell:
        creates: "{{home}}/.local/bin/sphinx-build"
        cmd: |
          pipx install sphinx
          pipx inject sphinx sphinxcontrib-needs
    # # pipx install blocked by pipx issue 402:
    # # https://github.com/pipxproject/pipx/issues/402
    # - name: Ensure borgbackup dependencies are installed
    #   apt:
    #     pkg:
    #       - libssl-dev
    #       - python3-dev
    #       - libacl1
    #       - libacl1-dev
    # - name: Ensure borgmatic is installed via pipx
    #   tags: backup
    #   shell:
    #     creates: "{{home}}/.local/bin/borgmatic"
    #     cmd: pipx install borgmatic


