---
- hosts: all
  tasks:
    - name: Ensure pipx is installed
      become: yes
      apt:
        pkg: pipx
    - name: Ensure pipx is in $PATH
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pipx"
        block: |
          export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
    - name: Ensure sphinx is installed via pipx
      shell:
        creates: "{{ ansible_env.HOME }}/.local/bin/sphinx-build"
        cmd: |
          pipx install sphinx
          pipx inject sphinx sphinxcontrib-needs

