---
- hosts: all
  tasks:
  - name: Install plantuml deps
    become: true
    apt:
      pkg:
        - openjdk-11-jre-headless
        - graphviz
      state: latest
  - name: Ensure plantuml jar folder exists
    become: true
    file:
      path: /opt/plantuml/jar/
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'
  - name: Download plantuml latest
    get_url:
      url: https://sourceforge.net/projects/plantuml/files/latest/download
      dest: /opt/plantuml/jar/plantuml.jar
      mode: '0755'
  # TODO: Check install via java -jar /opt/plantuml/jar/plantuml.jar -v
  # TODO: Copy over ~/bin/plantuml to wrap calls
