---
- name: Install PlantUML in /opt/plantuml
  hosts: dev
  tags: [dev, doc, x11, plantuml]
  tasks:
  - name: Install plantuml deps
    become: true
    apt:
      pkg:
        - openjdk-11-jre-headless
        - graphviz
      state: latest
  - name: Ensure plantuml jar folder exists
    become: true
    file:
      path: /opt/plantuml/jar/
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'
  - name: Download plantuml
    vars:
      plantuml:
        # Latest available via:
        # https://sourceforge.net/projects/plantuml/files/latest/download
        version: 1.2020.8
        checksum: sha256:3c30deb313f3027e31746336de7789047a2eb8acef7f4032640db01646437b76
    get_url:
      dest: /opt/plantuml/jar/plantuml.jar
      force: no
      url: "https://sourceforge.net/projects/plantuml/files/plantuml.{{ plantuml.version }}.jar/download"
      checksum: "{{ plantuml.checksum }}"
      mode: '0755'
  # TODO: Check install via java -jar /opt/plantuml/jar/plantuml.jar -v
  # TODO: Copy over ~/bin/plantuml to wrap calls
