---
- name: Run postgres database using docker-compose, systemd
  hosts: servers
  tasks:
    - name: Ensure gitea docker network exists
      docker_network:
        name: gitea
    - name: Install postgres docker-compose.yml in /opt/postgres/
      become: yes
      copy:
        src: "{{ playbook_dir}}/postgres-compose/docker-compose.yml"
        dest: /opt/postgres/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'
        validate: docker-compose -f %s config
    # From systemd ansible example
    # https://stackoverflow.com/a/40114458
    - name: Install postgres systemd unit file
      become: yes
      copy:
        src: "{{ playbook_dir}}/postgres-compose/postgres-docker.service"
        dest: /etc/systemd/system/postgres-docker.service
    - name: Enable postgres service
      become: yes
      systemd:
        name: postgres-docker
        enabled: yes
        daemon_reload: yes
