version: "3"

services:
  postgres:
   image: postgres:11
   container_name: postgres
   restart: always
   environment:
     - POSTGRES_USER=gitea
     - POSTGRES_PASSWORD=gitea
     - POSTGRES_DB=gitea
   networks:
     - gitea
   volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  gitea:
    external: true
