---
- name: Email (mbsync, mu4e)
  hosts: dev
  tags: email
  tasks:
    - name: Install mail fetchers (no X)
      become: true
      apt:
        pkg:
          - isync
          - maildir-utils
    - name: Deploy the mbsync config via stow
      shell:
        creates: "{{home}}/.mbsyncrc"
        cmd: "stow --dir ~/dev/conf/jibyconf/stow --target {{home}}/ mbsync"
    - name: Ensure maildir is created
      file:
        path: "{{home}}/.mail/jiby.tech"
        state: directory
        mode: '0755'
    - name: Fetch all mail
      tags: [never, slow, gpg-unlocked]
      shell:
        creates: "{{home}}/.mail/jiby.tech/Inbox"
        cmd: "mbsync -a"
    - name: Index mail via mu
      tags: [never, slow, gpg-unlocked]
      shell:
        # creates: "{{home}}/.mbsyncrc"
        cmd: "mu init --maildir ~/.mail/jiby.tech/ && mu index"


# TODO IMAP IDLE mail monitor triggering mbsync
# See https://imapclient.readthedocs.io/en/2.1.0/advanced.html?highlight=idle
# or smaller: https://gist.github.com/shimofuri/4348943
