---
- name: Password manager (gpg2, pass)
  hosts: dev
  tags: pass-manager
  tasks:
    - name: Ensure password manager installed
      become: yes
      apt:
        pkg:
          - gpgv2
          - pass
          - git
          - pass-extension-otp
    - name: Ensure password manager X11 extensions installed
      tags: x11
      become: yes
      apt:
        pkg:
          - suckless-tools
          - xdotool
    - name: Export GPG key
      local_action:
        module: shell
        creates: "{{ playbook_dir}}/../data/private_key.asc"
        cmd: "gpg --no-tty --output {{ playbook_dir}}/../data/private_key.asc --armor --export-secret-key jb@jiby.tech"
    - name: Copy GPG key
      copy:
        src: "{{ playbook_dir}}/../data/private_key.asc"
        dest: /tmp/private_key.asc
        mode: '0600'
    - name: Import GPG key
      shell: gpg --no-tty --batch --import /tmp/private_key.asc
    - name: Delete GPG key file on target
      file:
        path: /tmp/private_key.asc
        state: absent
    - name: Delete local export of GPG key
      local_action:
        module: file
        path: "{{ playbook_dir}}/../data/private_key.asc"
        state: absent
