---
- name: Run gitea (~github) using docker-compose, systemd
  hosts: servers
  tasks:
    - name: Ensure gitea docker network exists
      docker_network:
        name: gitea
    - name: Install gitea docker-compose.yml in /opt/gitea/
      become: yes
      copy:
        src: "{{ playbook_dir}}/gitea-compose/docker-compose.yml"
        dest: /opt/gitea/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'
        validate: docker-compose -f %s config
    # From systemd ansible example
    # https://stackoverflow.com/a/40114458
    - name: Install gitea systemd unit file
      become: yes
      copy:
        src: "{{ playbook_dir}}/gitea-compose/gitea-docker.service"
        dest: /etc/systemd/system/gitea-docker.service
    - name: Enable gitea service
      become: yes
      systemd:
        name: gitea-docker
        enabled: yes
        daemon_reload: yes
